# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_auto_20190201_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='second_app.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
    ]
