# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-01 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_auto_20190201_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
