# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-01 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0006_auto_20190201_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='second_app.Order'),
            preserve_default=False,
        ),
    ]
